---
services:
  app:
    build: .
    ports: ['${WEB_SERVER_PORT}:${WEB_SERVER_PORT}']
    env_file: [.env]
    environment:
      - WEB_SERVER_PORT=${WEB_SERVER_PORT}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    command: [./main]
